### ISSUE TITLE
Output files return empty

### ISSUE THREAD

**Issue by dtiezzi** [Clarivate-SAR/wos-amr#4]
Not successful using the example data. The output files are empty.

**Comment by gneissone** [comment]
@dtiezzi I expect this is an issue with credentials. I pushed a new commit https://github.com/Clarivate-SAR/wos-amr/commit/c23fec461702fc4962e415724699840575627513 that will return the XML message if there's an error parsing the response. 

Please try the updated code and let me know if the problem is something besides credentials. If the issue is credentials please reach out to your Clarivate account manager. Please note that AMR has its own credentials, they are not the same as your login credentials for the Web of Science platform.

**Comment by dtiezzi** [comment]
Dear Ben

Thanks for update the code. The problem was due to credentials and not the API itself.

Best regards

daniel


Daniel Tiezzi, MD, PhD
Assistant ProfessorProfessor
Department of Gynecology and Obstetrics
Breast Disease Division
Ribeirão Preto School of Medicine
University of São Paulo
Tel.: 16 3602-2488
e-mail: dtiezzi@usp.br

**Comment by ozaltun** [comment]
Hi,

I have the same problem. When I run:

`python3 lookup_ids.py ids_example.csv output.csv`

The output file is empty. 

Best,

Bora Ozaltun

**Comment by gneissone** [comment]
Thank you, I followed up via email. I have also pushed https://github.com/Clarivate-SAR/wos-amr/commit/7b5335aa1563afa2e5666b9b71ef15e4cf860716 which will return more information on these types of issues.
